# Lab 2: numpy

#### Practice Exercise 1

Create the following NumPy arrays: 
1. A 1-D array called zeros having 10 elements and all the elements are set to zero. 
2. A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’. 
3. A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int. 
4. Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7,  0,  -2,  3.4,  10.6,  0,  -19 99.9 13 
5. A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float


In [135]:
import numpy as np
zeros= np.zeros([10])
vowels = np.array(['a','e','i','o','u'])
ones= np.array([[1,1,1,1,1],
               [1,1,1,1,1]])
myarray1 = np.array([[ 2.7,  0,  -2],
                     [ 3.4,  10.6,  0],
                     [ -19, 99.9, 13]]) 
myarray2 = np.arange(4, 61, 4, dtype=float)
myarray3 = myarray2.reshape(3,5)



Using the arrays created in Question above, write NumPy commands for the following: 
1. Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2. 
2. Reshape the array ones to have all the 10 elements in a single row. 
3. Display the 2nd and 3rd element of the array vowels. 
4. Display all elements in the 2nd and 3rd row of the array myarray1. 
5. Display the elements in the 1st and 2nd column of the array myarray1. 
6. Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1. 
7. Reverse the array of vowels.

In [138]:
print('Q1: ')
print("Dimensions of zeros:", zeros.ndim)
print("Dimensions of vowels:", vowels.ndim)
print("Dimensions of ones:", ones.ndim)
print("Dimensions of myarray1:", myarray1.ndim)
print("Dimensions of myarray2:", myarray2.ndim)
print("Dimensions of myarray3:", myarray3.ndim)
print("------------------------------------------")
print("Shape of zeros:", zeros.shape)
print("Shape of vowels:", vowels.shape)
print("Shape of ones:", ones.shape)
print("Shape of myarray1:", myarray1.shape)
print("Shape of myarray2:", myarray2.shape)
print("Shape of myarray3:", myarray3.shape)
print("------------------------------------------")
print("Size of zeros:", zeros.size)
print("Size of vowels:", vowels.size)
print("Size of ones:", ones.size)
print("Size of myarray1:", myarray1.size)
print("Size of myarray2:", myarray2.size)
print("Size of myarray3:", myarray3.size)
print("------------------------------------------")
print("The data type of array zeros:", zeros.dtype)
print("The data type of array vowels:", vowels.dtype)
print("The data type of array ones:", ones.dtype)
print("The data type of array myarray1:", myarray1.dtype)
print("The data type of array myarray2:", myarray2.dtype)
print("The data type of array myarray3:", myarray3.dtype)
print("------------------------------------------")
print('Q2: ')
ones2 = ones.reshape(1,10)
print(ones2)
print("------------------------------------------")
print('Q3: ')
second_element = vowels[1] 
third_element = vowels[2]   
print("2nd element of array vowels:", second_element)
print("3rd element of array vowels:", third_element)
print("------------------------------------------")
print('Q4: ')
print('the 2nd and 3rd row of the array myarray1')
print(myarray1[1:3,:])
print("------------------------------------------")
print('Q5: ')
print('the 1st and 2nd column of the array myarray1')
print(myarray1[:, 0:2])
print("------------------------------------------")
print('Q6: ')
print('the 1st column of the 2nd and 3rd row of the array myarray1')
print(myarray1[1:3, 0])
print("------------------------------------------")
print('Q7: ')
print('the reversed array of vowels: ')
reversed_vowels = vowels[::-1]
print(reversed_vowels)

Q1: 
Dimensions of zeros: 1
Dimensions of vowels: 1
Dimensions of ones: 2
Dimensions of myarray1: 2
Dimensions of myarray2: 1
Dimensions of myarray3: 2
------------------------------------------
Shape of zeros: (10,)
Shape of vowels: (5,)
Shape of ones: (2, 5)
Shape of myarray1: (3, 3)
Shape of myarray2: (15,)
Shape of myarray3: (3, 5)
------------------------------------------
Size of zeros: 10
Size of vowels: 5
Size of ones: 10
Size of myarray1: 9
Size of myarray2: 15
Size of myarray3: 15
------------------------------------------
The data type of array zeros: float64
The data type of array vowels: <U1
The data type of array ones: int64
The data type of array myarray1: float64
The data type of array myarray2: float64
The data type of array myarray3: float64
------------------------------------------
Q2: 
[[1 1 1 1 1 1 1 1 1 1]]
------------------------------------------
Q3: 
2nd element of array vowels: e
3rd element of array vowels: i
------------------------------------------
Q4: 


Using the arrays created in Question above, write NumPy commands for the following:
1. Divide all elements of array ones by 3. 
2. Add the arrays myarray1 and myarray2. 
3. Subtract myarray1 from myarray2 and store the result in a new array. 
4. Multiply myarray1 and myarray2 elementwise. 
5. Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3. 
6. Divide myarray1 by myarray2. 
7. Find the cube of all elements of myarray1 and divide the resulting array by 2. 
8. Find the square root of all elements of myarray2   and divide the resulting array by 2. The result  should be rounded to two places of decimals.

In [141]:
print('Q1: ')
ones3 = ones / 3
print(ones3)

print("------------------------------------------")
print('Q2: ')
sliced_array= myarray2[:9].reshape(3,3)
total_myarrays = myarray1 + sliced_array
print(total_myarrays)
print("------------------------------------------")
print('Q3: ')
total_subtracted_array= sliced_array - myarray1
print(total_subtracted_array)
print("------------------------------------------")
print('Q4: ')
product_array = sliced_array * myarray1
print(product_array)
print("------------------------------------------")
print('Q5: ')
myarray3 = np.dot(myarray1, sliced_array)
print(myarray3)
print("------------------------------------------")
print('Q6: ')
divided_total = myarray1 / sliced_array
print(divided_total)
print("------------------------------------------")
print('Q7: ')
cubed_array = []
for row in myarray1:
    for element in row:
        cubed_array.append(element **3)

cubed_array=np.array(cubed_array)
divided_total = cubed_array / 2
print(divided_total)
print("------------------------------------------")
print('Q8: ')
square_array = []
squared_array = np.array(myarray2 +2 )
total = np.round(squared_array / 2, 2)
print(total)

Q1: 
[[0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]]
------------------------------------------
Q2: 
[[  6.7   8.   10. ]
 [ 19.4  30.6  24. ]
 [  9.  131.9  49. ]]
------------------------------------------
Q3: 
[[  1.3   8.   14. ]
 [ 12.6   9.4  24. ]
 [ 47.  -67.9  23. ]]
------------------------------------------
Q4: 
[[  10.8    0.   -24. ]
 [  54.4  212.     0. ]
 [-532.  3196.8  468. ]]
------------------------------------------
Q5: 
[[ -45.2  -42.4  -39.6]
 [ 183.2  239.2  295.2]
 [1886.4 2262.  2637.6]]
------------------------------------------
Q6: 
[[ 0.675       0.         -0.16666667]
 [ 0.2125      0.53        0.        ]
 [-0.67857143  3.121875    0.36111111]]
------------------------------------------
Q7: 
[ 9.841500e+00  0.000000e+00 -4.000000e+00  1.965200e+01  5.955080e+02
  0.000000e+00 -3.429500e+03  4.985015e+05  1.098500e+03]
------------------------------------------
Q8: 
[ 3.  5.  7.  9. 11. 

Using the arrays created above, write NumPy commands for the following: 
1. Find the transpose of ones and myarray2. 
2. Sort the array vowels in reverse. 
3. Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.

In [160]:
print('Q1: ')
print('the transpose of ones:', ones.T)
print('the transpose of ones: ' , myarray2.T)
print("------------------------------------------")
print('Q2: ')
reversed_vowels = np.sort(reversed_vowels)
print(reversed_vowels)
print("------------------------------------------")
print('Q3: ')
sorted_array = np.sort(myarray1, axis=0)
print(sorted_array)


Q1: 
the transpose of ones: [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
the transpose of ones:  [ 4.  8. 12. 16. 20. 24. 28. 32. 36. 40. 44. 48. 52. 56. 60.]
------------------------------------------
Q2: 
['a' 'e' 'i' 'o' 'u']
------------------------------------------
Q3: 
[[-19.    0.   -2. ]
 [  2.7  10.6   0. ]
 [  3.4  99.9  13. ]]


Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result. 

In [184]:
myarray4 = np.arange(-1, -1  + 0.25 * 42, 0.25).reshape(14,3)
splitted_array = np.array_split(myarray4, 3, axis=0)

print(splitted_array)

[array([[-1.  , -0.75, -0.5 ],
       [-0.25,  0.  ,  0.25],
       [ 0.5 ,  0.75,  1.  ],
       [ 1.25,  1.5 ,  1.75],
       [ 2.  ,  2.25,  2.5 ]]), array([[2.75, 3.  , 3.25],
       [3.5 , 3.75, 4.  ],
       [4.25, 4.5 , 4.75],
       [5.  , 5.25, 5.5 ],
       [5.75, 6.  , 6.25]]), array([[6.5 , 6.75, 7.  ],
       [7.25, 7.5 , 7.75],
       [8.  , 8.25, 8.5 ],
       [8.75, 9.  , 9.25]])]


Using the myarray4 created in the above questions, write commands for the following: 
1. Find the sum of all elements. 
2. Find the sum of all elements row wise
3. Find the sum of all elements column wise. 
4. Find the max of all elements. 
5. Find the min of all elements in each row. 
6. Find the mean of all elements in each row. 
7. Find the standard deviation column wise.

In [214]:
print('Q1: ')
total = 0

for rows in myarray4:
    for elements in rows:
        total = total + elements

print(total)

print('Q2: ')
sum_rows = np.sum(myarray4,axis=1)
print(sum_rows)

print('Q3: ')
sum_column = np.sum(myarray4,axis=0)
print(sum_column)

print('Q4: ')
max_value = np.max(myarray4)
print(max_value)

print('Q5: ')
min_value = np.min(myarray4)
print(min_value)

print('Q6: ')
mean_value = np.mean(myarray4 , axis=1)
print('The mean of each row is:', mean_value)

print('Q7: ')

std_column = np.std(myarray4, axis=0)  
print('Standard deviation of each column:', std_column)

Q1: 
173.25
Q2: 
[-2.25  0.    2.25  4.5   6.75  9.   11.25 13.5  15.75 18.   20.25 22.5
 24.75 27.  ]
Q3: 
[54.25 57.75 61.25]
Q4: 
9.25
Q5: 
-1.0
Q6: 
The mean of each row is: [-0.75  0.    0.75  1.5   2.25  3.    3.75  4.5   5.25  6.    6.75  7.5
  8.25  9.  ]
Q7: 
Standard deviation of each column: [3.02334666 3.02334666 3.02334666]


#### Practice Exercise 2
Read the coordinates of the capital cities of the world from the country-capital-lat-long-population.csv file. Use NumPy to print the name and coordinates of the capital city closest to the Saudi Arabia capital - Riyadh.

Note that:

1. The Country Name for Saudi Arabia is given as Saudi Arabia in the data.
2. The ‘closeness’ of capital cities from the Saudi Arabia capital is based on the Euclidean distance of their coordinates to those of the Saudi Arabia capital.


Hints:

1. Use read_html() from the Pandas library to read the table.
2. Use the to_numpy() function of the Pandas DataFrame class to convert a DataFrame to a Numpy array
3. Use broadcasting to compute the euclidean distance of capital cities from Riyadh.

In [254]:
import pandas as pd
import numpy as np
country_capital = pd.read_csv("country-capital-lat-long-population.csv")

riyadh_data = country_capital[country_capital['Country'] == 'Saudi Arabia']
riyadh_lat = riyadh_data['Latitude'].values[0]
riyadh_long = riyadh_data['Longitude'].values[0]
capitals_lat = country_capital['Latitude'].to_numpy()
capitals_long = country_capital['Longitude'].to_numpy()
distances = np.sqrt((capitals_lat - riyadh_lat) ** 2 + (capitals_long - riyadh_long) ** 2)
closest_index = np.argmin(distances)
closest_capital = country_capital['Capital City'].values[closest_index]
closest_lat = capitals_lat[closest_index]
closest_long = capitals_long[closest_index]
print(f"The closest capital city to Riyadh is {closest_capital} at coordinates ({closest_lat}, {closest_long}).")



The closest capital city to Riyadh is Ar-Riyadh (Riyadh) at coordinates (24.6905, 46.7096).


#### Practical Exercise 2

Use NumPy to:

1. Print the names of the countries of the top 10 capital cities closest to the US capital - Washington DC.

2. Create and print a NumPy array containing the coordinates of the top 10 cities.

In [269]:
import pandas as pd
import numpy as np

df = pd.read_csv("country-capital-lat-long-population.csv")
df.columns = df.columns.str.strip()
dc_lat = df[df['Country'] == 'United States of America']['Latitude'].values[0]
dc_long = df[df['Country'] == 'United States of America']['Longitude'].values[0]

capitals_lat = df['Latitude'].to_numpy()  
capitals_long = df['Longitude'].to_numpy() 
countries = df['Country'].to_numpy() 

distances = np.sqrt((capitals_lat - dc_lat) ** 2 + (capitals_long - dc_long) ** 2)

closest_indices = np.argsort(distances)[:10]

print("Top 10 closest capital cities to Washington D.C.:")
for index in closest_indices:
    capital_name = df['Capital City'].values[index]  
    print(f"Country: {countries[index]}, Capital: {capital_name}")

top_10_coordinates = np.array(list(zip(capitals_lat[closest_indices], capitals_long[closest_indices])))
print("\nCoordinates of the top 10 closest capital cities (Latitude, Longitude):")
print(top_10_coordinates)



Top 10 closest capital cities to Washington D.C.:
Country: United States of America, Capital: Washington, D.C.
Country: Canada, Capital: Ottawa-Gatineau
Country: Bahamas, Capital: Nassau
Country: Bermuda, Capital: Hamilton
Country: Cuba, Capital: La Habana (Havana)
Country: Turks and Caicos Islands, Capital: Cockburn Town
Country: Cayman Islands, Capital: George Town
Country: Haiti, Capital: Port-au-Prince
Country: Jamaica, Capital: Kingston
Country: Dominican Republic, Capital: Santo Domingo

Coordinates of the top 10 closest capital cities (Latitude, Longitude):
[[ 38.8951 -77.0364]
 [ 45.4166 -75.698 ]
 [ 25.0582 -77.3431]
 [ 32.2915 -64.778 ]
 [ 23.1195 -82.3785]
 [ 21.4612 -71.1419]
 [ 19.2866 -81.3744]
 [ 18.5392 -72.335 ]
 [ 17.997  -76.7936]
 [ 18.4896 -69.9018]]
